### ISSUE TITLE
CI: repair #23950 durable-stimulus exhaustiveness and test module wiring

### ISSUE THREAD

**Issue by jeong-sik** [jeong-sik/masc#23959]
## Symptom

Latest main commit `4a7d9f75c233d97b2c12e304bce751c7136e6b19` CI run `29079174277` fails Lint/Health after #23950:

```text
bin/masc_completion_trust_eval.ml:232-248
non-exhaustive match: Yielded_to_durable_stimulus _
```

```text
test/test_keeper_event_queue.ml:1043
Error: Unbound module Keeper_chat_queue
```

## Reproduction

Inspect the failed jobs in run `29079174277` or run the CI-owned lint/health build targets on current main.

## Suspected cause

#23950 added `Runtime_agent.Yielded_to_durable_stimulus` and queue assertions, but did not update the completion-trust projection or the relevant test stanza/library wiring.

## Tried

Confirmed the failures occur after the STATE/BDI purge's Meta Guards, Fundamental, version truth, RFC index, and spec-line-ref gates are green. Searched open PRs/issues for the two symbols and #23950; no existing follow-up was found. Kept separate because this is subsequent #23950 fallout, not #23929 purge behavior.

**Comment by jeong-sik** [comment]
해결 확인 후 닫습니다. #23958 (merge 381add81c6)에서 `Yielded_to_durable_stimulus` exhaustiveness와 `Keeper_chat_queue` 테스트 모듈 경계를 수정했습니다. 2026-07-10 KST main 11f33d412b CI run 29079657771에서 Lint의 `Build with warnings as errors`, OCaml 5.5 Build Canary, Health가 모두 통과해 두 컴파일 회귀가 해소되었음을 확인했습니다.
