### ISSUE TITLE
main does not compile: tool_schemas_schedule update unbound (#32141) + fusion_sink signature mismatch (#32146)

### ISSUE THREAD

**Issue by jeong-sik** [jeong-sik/masc#32164]
## What

`main` does not compile: the `Full validation` Build step fails on `origin/main` itself, independent of any branch's changes.

Two independent breakages:

1. `lib/tool_schemas/tool_schemas_schedule.ml:6` — `Unbound value Tool_schemas_schedule_toml.update`, and `tool_schemas_schedule_toml.ml:29` — `unused value update` (warning 32 as error). Introduced by #32141 (71bcd8163e, "feat(schedule): add TUI create and atomic update").
2. `lib/fusion/fusion_sink.ml:517` — signature mismatch on `?tool_trace`. Introduced by #32146 (9d6483c8ee, "feat(fusion): persist actual tool execution traces").

## Reproduction (2026-09-01, local clone reset to origin/main)

```
$ dune build lib/tool_schemas/
File "lib/tool_schemas/tool_schemas_schedule.ml", line 6, characters 20-53:
Error: Unbound value Tool_schemas_schedule_toml.update
File "lib/tool_schemas/tool_schemas_schedule_toml.ml", line 29, characters 4-10:
Error (warning 32 [unused-value-declaration]): unused value update.
```

CI evidence: run 33453601086 (branch task1202-registry-row, prompt-clean single-file change) `Full validation` → step 8 `Build` failure with these exact errors; the same commit builds clean when the two files above are reverted locally.

## Why it matters

Every PR now fails `Full validation` at Build regardless of its own content — attribution is masked and the merge queue is blocked. Also `main`'s own scheduled runs fail the same way (run 33453606497).

## Fix direction

- #32141: export `update` from `Tool_schemas_schedule_toml` (mli) or stop referencing it in `tool_schemas_schedule.ml`.
- #32146: reconcile `fusion_sink.ml:517` optional-arg signature (`?tool_trace`) with its .mli.

```masc-triage
kind: defect
area: ci
impact: degrades
root: ssot
must-do: true
```

**Comment by jeong-sik** [comment]
Breakage map completed (2026-09-01 ~00:55Z, local origin/main reproduction + `git log -S` per symbol). **All four failures trace to two PRs; three of four to #32141 alone: (#32141, 71bcd8163e)**

1. `lib/tool_schemas/tool_schemas_schedule.ml:6` — `Unbound value Tool_schemas_schedule_toml.update` (+`_toml.ml:29` unused `update`, warning 32). `git log -S` → 71bcd8163e only.
2. `bin/masc_tui_types.ml:439` — `Unbound module Time_codec`: `Option.bind row.sch_expires_at_iso Time_codec.parse_rfc3339_opt` references a module that has **zero declarations anywhere in lib/ or bin/** (`grep -rln 'module Time_codec' lib/ bin/` → empty). Also 71bcd8163e.
3. `test/test_board_rest_routes.ml:131` — `Unbound Server_routes_http_routes_activity.schedule_stamp_operator_actor`: the symbol **does exist** in `lib/server/server_routes_http_routes_activity.ml:25` and `.mli:51`; it surfaces as Unbound only because upstream compilation dies first. Also introduced by 71bcd8163e.
4. `lib/fusion/fusion_sink.ml:517` — `?tool_trace` signature mismatch (#32146, 9d6483c8ee). Independent of #32141.

Practical consequence: **fixing #32141's three sites (or reverting it) restores main compilation except fusion_sink**, which needs its own one-line mli reconciliation. A revert of 71bcd8163e would clear 1-3 in one move — worth considering given main has been unbuildable since it landed.

(cc lane-smith's fleet summary 00:23Z: its "2호" is `bin/masc_tui_http.ml:1975` (#32130, c108760a3c) — a *fifth*, separate breakage being fixed by codex-mcp-client. #32164 tracks 1-4 here.)

**Comment by jeong-sik** [comment]
main compile repair confirmed (2026-09-01, first-hand verification):

- `origin/main` @ 6a8ca81587 (includes bb430eb27b — #32161 "main compile repair"): full-repo `dune build` **and** `dune build test/test_board_rest_routes.ml` both EXIT=0, zero errors. The same commands on f065b98ea5 (pre-repair main) reproduced this issue's exact errors, so the before/after attribution is first-hand, not inherited.
- Repair attribution: bb430eb27b (#32161) cleared the #32141 sites (incl. `Time_codec` and the schedule `update` pair); follow-up merges #32138/#32158/#32136 and the #32130 caller fix (codex) landed on top.

Still red on main but **outside this issue's scope**: the Lint step `Check Keeper runtime setting registry` (`MASC_KEEPER_RATE_LIMIT_BACKOFF_CAP_SEC` unregistered) — tracked in #32156, fixed by PR #32163 (data-only 9-line registry row; its CI run 33453601086 shows that Lint step green), awaiting merge.

Closing as completed on the compile claim. Reopening is appropriate if a fresh main dispatch shows a compile failure again.
