### ISSUE TITLE
P0: main test compile remains broken after #26278 — two Otel_metric_store references

### ISSUE THREAD

**Issue by jeong-sik** [jeong-sik/masc#26293]
## 증상

PR #26285의 `Build and Test`가 OCaml 컴파일에서 중단됩니다.

```text
File "test/test_keeper_wake_turn_context.ml", line 385
Error: Unbound module Otel_metric_store
```

## 현재 main 재현

확인 SHA `d2cfc46584ab0bab28a2c595079d4fd5508f7d23`의 `test/test_keeper_wake_turn_context.ml:353,359`는 여전히 `Otel_metric_store.get_metric_value`를 호출합니다. 모듈 공개 이름은 `Otel_metric_store_core`입니다.

#26278은 같은 테스트의 앞선 두 호출(332,338)만 바꿔 컴파일 복구를 완료하지 못했습니다. 따라서 이 파일을 컴파일하는 모든 PR이 base 오류로 막힙니다. #26285의 새 prompt test가 원인은 아니며, CI 러너 문제도 아닙니다.

## 수리와 검증

남은 두 호출을 canonical module로 바꾸고 `@check`가 이 테스트 executable을 실제 컴파일하는 CI run으로 확인해야 합니다. 현재 PR의 unrelated prompt 흐름에 억지로 섞지 말고, 작은 P0 compile-fix PR로 처리하세요.

관련: #26278, #26285

```masc-triage
kind: defect
area: ci
impact: internal
root: 
must-do: false
```

**Comment by jeong-sik** [comment]
남아 있던 두 호출이 canonical 모듈로 바뀌어 컴파일 차단이 해소됐다.

근거: test/test_keeper_wake_turn_context.ml:499,505,521,527 이 모두 Otel_metric_store_core.get_metric_value 를 호출하고 Otel_metric_store 참조는 0건이다.
