### ISSUE TITLE
머지 결과물을 머지 전에 빌드하지 않아 semantic conflict가 main을 깨뜨림 (#25420 × #25442) — merge queue 필요

### ISSUE THREAD

**Issue by jeong-sik** [jeong-sik/masc#25481]
## 증상

required check (`CI Gate`) 가 green 인 PR 이 머지된 뒤 `dune build @all` 이 깨진다. 테스트 전용 소스의 **컴파일 에러**가 게이트를 통과한다.

## 실제 발생 (2026-07-21)

#25420 (`refactor(keeper): move test-only Keeper_registry vals behind For_testing`) 머지 직후 main:

```
File "test/test_keeper_registry_admission_no_suspend.ml", line 61, characters 4-12:
61 |     KR.clear ();
Error: Unbound value KR.clear
```

- #25420 은 `clear` 를 포함한 8개 val 을 `For_testing` 로 옮기고 테스트 호출 사이트 ~36개를 갱신했으나, 이 파일이 PR 변경 목록에 없었다 (1개 누락).
- PR CI 는 green 이었다. 해당 테스트는 `test/stanzas/test_keeper_registry_admission_no_suspend.inc` 로 배선된 평범한 `(test ...)` 스탠자이고 `enabled_if` 제외도 없다 — dead target 이 아니다.
- 복구: #25480.

## 재현 조건

테스트 실행파일만 참조하는 심볼을 리네임/이동하고, 호출 사이트 하나를 놓친다. `dune build @default @check` 는 통과하고 `dune build @all` 만 실패한다.

## 추정 원인

`@default` 는 `(test ...)` 스탠자의 실행파일을 전부 포함하지 않는다. 따라서 게이트가 "빌드된다"고 말하는 범위와 개발자가 로컬에서 `@all` 로 확인하는 범위가 다르다.

## 제안

`CI Gate` 경로에 `dune build @all` 을 추가한다.

**단, 선행 확인이 필요하다**: 지금 main 에서 `@all` 이 이미 다른 이유로 실패할 가능성이 있다. 게이트에 넣기 전에 clean main 에서 `dune build @all` 을 한 번 돌려 기존 실패 목록을 확보하고, 있으면 그것부터 정리해야 한다. 그 확인 없이 게이트만 조이면 모든 PR 이 빨간불이 된다.

빌드 시간이 문제라면 대안은 `@check` 범위를 테스트 디렉터리까지 넓히는 것 (`dune build @check` 는 타입 체크만 하므로 링크 비용이 없다). 이쪽이 비용 대비 탐지율이 낫다.

## 왜 지금 기록하는가

이번 세션에서 이 함정 때문에 **검증을 거친 PR 이 main 을 깨뜨렸다**. 리뷰어(사람이든 에이전트든)가 "CI green" 을 빌드 증거로 받아들이는 한 재발한다. 탐지를 사람 주의력이 아니라 게이트로 옮겨야 한다.

관련: #25420, #25480

```masc-triage
kind: gap
area: ci
impact: internal
root: 
must-do: false
```

**Comment by jeong-sik** [comment]
## 정정: 최초 진단이 틀렸습니다

이 이슈를 열 때 저는 원인을 "`CI Gate` 가 `@default @check` 만 빌드해서 테스트 전용 소스의 컴파일 에러가 통과한다" 로 적었습니다. **틀렸습니다.** 근거를 확인하지 않고 알고 있던 함정에 끼워 맞춘 것입니다.

### 반증

1. main 의 실패 로그에 `Build and Test  Build  Error: Unbound value KR.clear` 가 있습니다 — `Build and Test` 는 그 테스트를 **정상적으로 컴파일합니다**. 빌드 범위 문제가 아닙니다.
2. #25420 의 PR 체크는 `Build and Test` 를 포함해 **전부 통과**했습니다 (skip 아님, 실제 SUCCESS).

### 실제 원인: 깨끗하게 병합되는 두 PR 사이의 semantic conflict

```
git log --oneline --diff-filter=A -- test/test_keeper_registry_admission_no_suspend.ml
→ 505f2cd3d5 fix(keeper): stop holding the admission slot mutex across a fiber suspension (#25442)

git cat-file -e bd85f786b6:test/test_keeper_registry_admission_no_suspend.ml
→ 없음   (bd85f786b6 = #25420 의 merge-base)
```

- **#25442** 가 `Keeper_registry.clear` 의 **새 호출자**를 담은 파일을 추가했습니다.
- **#25420** 은 그 사이 별도 브랜치에서 `clear` 를 `For_testing` 뒤로 **옮겼습니다**.
- 두 PR 은 **파일이 겹치지 않으므로** git 이 충돌 없이 병합합니다.
- `strict: false` (브랜치가 main 최신일 필요 없음) 이므로 **어느 쪽 CI 도 두 변경의 조합을 빌드한 적이 없습니다.**

#25420 의 CI 가 초록이었던 것은 착시가 아니라 정확합니다 — 그 트리에는 그 호출자가 존재하지 않았습니다.

### 그래서 원래 제안(`@all` 추가)은 이 사고를 막지 못합니다

`Build and Test` 는 이미 그 테스트를 빌드합니다. 파일이 없었을 뿐입니다. `@all` 을 추가해도 결과는 같습니다.

### 올바른 방향

이 클래스(심볼 이동 ↔ 다른 PR 이 추가한 새 호출자)는 **머지 결과물을 빌드해야만** 잡힙니다.

1. **GitHub merge queue** — 머지 직전에 "main + 이 PR" 조합을 실제로 빌드/테스트. 이 저장소처럼 머지 속도가 빠른 곳(오늘 1시간에 20+ 머지)에 가장 잘 맞습니다.
2. `strict: true` (require branches up to date) — merge queue 없이 가능한 대안이지만, 머지 하나가 열린 PR 전부를 무효화하므로 이 속도에서는 비용이 큽니다.

참고로 흔히 쓰는 완화책인 "merge-base 이후 main 이 바꾼 파일 ∩ PR 이 바꾼 파일" 교집합 검사도 **이 사고를 못 잡습니다**. #25420 의 교집합은 비어 있었습니다 — 문제의 파일은 #25420 이 건드리지 않았고 main 이 *새로 추가한* 파일이기 때문입니다. 파일 단위 교집합은 "네가 이름을 바꾸는 심볼의 새 호출자를 main 이 추가했다" 를 표현하지 못합니다.

실제로 이 사고를 잡은 것은 **머지된 트리에서의 `dune build @all` 실행** 이었습니다.

### 이 이슈의 범위 재정의

제목의 "@all" 프레이밍은 폐기합니다. 남는 요청은 **머지 결과물을 머지 전에 빌드하는 게이트(merge queue 우선)** 입니다.

**Comment by jeong-sik** [comment]
## 같은 근본의 두 번째 사례 — 이번엔 의존성 하한

#25330 검증에서 이 이슈와 **같은 원인의 다른 표현**이 나왔습니다. 기록해 둡니다.

- #25330 의 마지막 CI(2026-07-19T14:57Z) 는 green 이었고, 그 실행은 브랜치의 `dune-project` / `masc.opam` 선언대로 `agent_sdk.0.216.4` 를 해석했습니다(CI 로그 확인).
- 그 사이 `origin/main` 은 무관한 커밋으로 `agent_sdk >= 0.217.4` 로 하한을 올렸습니다.
- 0.217.4 에서 이 PR **자신의 새 테스트** `test_runtime_agent_resume_enforces_native_context_fit` 가 실패합니다 — `Invalid request (unknown): prepared request has no effective output-token ceiling`, 3/3 재현, 순수 PR head 와 PR+main 머지 트리 양쪽.

즉 초록 체크가 가리키는 것은 "이 PR 이 **자기 브랜치가 선언한 의존성 버전**에서 통과했다" 입니다. main 이 하한을 올린 뒤에는 그 초록이 현재 상태에 대해 아무것도 말해 주지 않습니다.

## 왜 별도 이슈로 열지 않는가

원인이 이 이슈와 동일합니다 — **머지 결과물을 머지 전에 빌드하지 않는다**. 앞선 사례(#25420 × #25442) 는 소스 심볼의 semantic conflict 였고, 이번은 **의존성 해석**의 semantic conflict 입니다. 둘 다 "PR 브랜치는 통과, 머지 후 조합은 실패" 이고, 둘 다 merge queue 가 잡습니다.

## 파생 제안 하나

merge queue 를 도입하기 전 임시 완화로, 최소한 **`dune-project` / `*.opam` 의 의존성 하한이 main 보다 낮은 PR** 을 표시하는 검사를 추가할 수 있습니다. 이건 파일 단위 교집합 검사와 달리 값 비교라서 저렴하고, 이번 케이스를 정확히 잡습니다.

근거: #25330 검증(2026-07-21).

**Comment by jeong-sik** [comment]
같은 모양이 또 났어요 (2026-09-08).

- #34163 (02:17 KST 머지) 이 `Runtime.validate_request_body_cap` 을 `int option` 으로 바꿨고, #34174 (08:10 KST 머지) 는 그 값을 `int` 로 읽어 이미지를 cap 에 맞췄어요.
- 둘 다 각자의 base 에서 pr-check 초록이었고, 텍스트 충돌이 없어서 GitHub 이 그냥 머지했어요. 머지 커밋에는 run 이 하나도 없어서(main 은 push 트리거가 release.yml 뿐) 로컬 빌드에서야 `lib/keeper/keeper_vision_tool.ml:498` 타입 오류로 드러났어요.
- 수정: #34214 (cap 없는 후보는 이미지를 그대로 받음).

머지 큐가 없으면 "두 번째 PR 을 머지 직전에 main 위에서 다시 @check" 가 최소한의 대체예요. 이번엔 8시간 창 안에 vision 쪽 PR 이 셋(#34140, #34163, #34174) 겹쳤어요.
