### ISSUE TITLE
test: liveness_recovery_2 logic failure surfaced after #12822 unblocked compile

### ISSUE THREAD

**Issue by jeong-sik** [jeong-sik/masc#12826]
## Context

PR #12822 unblocked the `dune build @check` failure in `test/test_keeper_supervisor.ml` (the `Masc_mcp.Env_config.KeeperSupervisor` Unbound module error). Once the binary compiles, the `liveness_recovery` test suite runs — and `liveness_recovery_2` fails with a logic error.

## Symptom

```
[FAIL]  liveness_recovery  2  should_attempt: Dead + elapsed -> true

ASSERT Dead + elapsed -> true
FAIL Dead + elapsed -> true
   Expected: 'true'
   Received: 'false'
```

`Sup.should_attempt_liveness_recovery` returns `false` where the test expects `true` after `Reg.mark_dead` plus sufficient elapsed time.

## Reproduce

```
git checkout main
dune build test/test_keeper_supervisor.exe
./_build/default/test/test_keeper_supervisor.exe test liveness_recovery
```

Expected: 6/6 OK. Actual: 5/6 OK, `liveness_recovery_2` FAIL.

## Root cause hypothesis

The implementation of `Sup.should_attempt_liveness_recovery` (lib/keeper/keeper_supervisor.ml) was added together with the test in #12803 (commit 851d9fb64d). Either:

1. The implementation has a guard that rejects "Dead + elapsed" when registry was just marked dead `~at:0.0` (clock skew vs default `now`).
2. The test setup (`Reg.mark_dead ~at:0.0` followed immediately by `should_attempt_liveness_recovery ~now`) does not match the production path the implementation expects.
3. Pre-condition (e.g. `liveness_recovery_attempts < max`, or required prior phase transition) is missing in the test seed.

## Why this surfaced now

The test file did not compile on main prior to #12822 because `Masc_mcp.Env_config.KeeperSupervisor.liveness_recovery_backoff_*` referenced a non-existent module path (`Env_config_keeper` lives in `masc_config` library, not `masc_mcp`). #12822 corrected the references; the file now compiles and runs, surfacing the lurking logic mismatch.

## Suggested fix

Read `lib/keeper/keeper_supervisor.ml::should_attempt_liveness_recovery` and reconcile with the test's mental model. Likely either the implementation needs a small relaxation, or the test needs to seed an additional pre-condition.

## Related

- #12803 — original PR introducing both the implementation and the test.
- #12822 — surfaced this failure.
